### ISSUE TITLE
Unexpected token export error while npm test

### ISSUE THREAD

**Issue by Aneelkumar97** [petecuttriss/spfx-jest-preset#1]
```
 FAIL  src\webparts\sample\tests\Sample.spec.tsx
  ● Test suite failed to run

    E:\SPFX\spfx-jest-preset-master\node_modules\@microsoft\sp-core-library\lib\index.js:11
    export { default as _BrowserDetection } from './BrowserDetection';
    ^^^^^^

    SyntaxError: Unexpected token export



      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (webparts/sample/components/Sample.tsx:709:76)
      at Object.<anonymous> (webparts/sample/tests/Sample.spec.tsx:8:16)


```

Error when I run 'npm test' with your repo.

**Comment by petecuttriss** [comment]
Hi AneelKumar97, 

Yes, that's correct.  This repo was setup whilst Andrew Connell and I investigated the issue that you are seeing.

I'll remove this repo so that it doesn't cause further confusion.

For your reference, you might want to refer to the following blog post and the associated comments.   Also, you may want to refer to the following Github issue.

http://www.andrewconnell.com/blog/enable-jest-testing-of-sharepoint-framework-projects-in-one-simple-step

https://github.com/SharePoint/sp-dev-docs/issues/2325

Regards
Pete
